In [1]:
import os
os.getcwd()

'/Users/rushana/Desktop/datascience-publicpolicy-2026'

In [2]:
import pandas as pd

demodata = pd.read_csv("/Users/rushana/Documents/GitHub/graspp_2025_spring/data/examples/module_3/democracy_gdp.csv")
demodata.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

In [3]:
ghg = pd.read_csv("/Users/rushana/Documents/GitHub/graspp_2025_spring/data/examples/module_2/ghg.csv")
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

In [4]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

In [5]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ["PK"]
)
gdp_data.head(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Pakistan,PAK,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Pakistan,PAK,2024,1478.772780,NaN,NaN,1
2,GDP per capita (current US$),Pakistan,PAK,2023,1360.324178,NaN,NaN,1
3,GDP per capita (current US$),Pakistan,PAK,2022,1538.322813,NaN,NaN,1
4,GDP per capita (current US$),Pakistan,PAK,2021,1455.319224,NaN,NaN,1

In [6]:
population_indicator = "SP.POP.TOTL"


country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS",  # Australia
    "PAK",  #Pakistan
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
321,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
322,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
323,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

In [7]:
demodata_subset = demodata[["country", "year",]]
demodata_subset.head()

  country  year
0     AFG  1990
1     AFG  1991
2     AFG  1992
3     AFG  1993
4     AFG  1994

In [25]:
ddcountrysubset = demodata.query("country == 'PAK'")
ddcountrysubset.head()

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
3010,PAK,1990,0.660,NaN,NaN,0.817,0.827,0.278,0.655,-0.514
3011,PAK,1991,0.644,NaN,NaN,0.817,0.827,0.280,0.655,-0.514
3012,PAK,1992,0.644,NaN,NaN,0.817,0.827,0.280,0.655,-0.514
3013,PAK,1993,0.648,NaN,NaN,0.817,0.827,0.281,0.655,-0.514
3014,PAK,1994,0.660,NaN,NaN,0.817,0.827,0.283,0.655,-0.514

In [24]:

ddyearsubset = demodata.query("year == 1998 and country == 'KOR'")
ddyearsubset.head()

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
1037,KOR,1998,0.851,8572.751,-4.9,0.143,0.254,0.919,0.923,2.535
1038,KOR,1998,0.851,8572.751,-4.9,0.143,0.254,0.919,0.923,2.535
1039,KOR,1998,0.851,8572.751,-4.9,0.143,0.254,0.919,0.923,2.535
1040,KOR,1998,0.851,8572.751,-4.9,0.143,0.254,0.919,0.923,2.535
1041,KOR,1998,0.851,8572.751,-4.9,0.143,0.254,0.919,0.923,2.535

In [27]:
demodata.query("year == 2002")["country"].unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [33]:
demodata.query("year == 2016")[["country", "year"]]

         country  year
26           AFG  2016
61           ARM  2016
96           AZE  2016
131   Asia (avg)  2016
166          BGD  2016
...          ...   ...
5015         TWN  2016
5016         TWN  2016
5017         TWN  2016
5556         UZB  2016
5591         VNM  2016

[160 rows x 2 columns]

In [34]:
demodata.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [37]:
demodata.rename({"country" : "Country"}, axis=1).head(2)

,Country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [38]:
demodata.rename({"year" : "Year"}, axis=1).head(2)

,country,Year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [50]:
demodata[demodata["country"] == "PAK"]
rename_country_map = {
    "AFG" : "Pashtun"
}

demodata.country.replace(rename_country_map)

0       Pashtun
1       Pashtun
2       Pashtun
3       Pashtun
4       Pashtun
         ...
5595        VNM
5596        VNM
5597        VNM
5598        VNM
5599        VNM
Name: country, Length: 5600, dtype: object